# Task 39 – NumPy: Array Sorting
**Reference:** https://www.w3schools.com/python/numpy_array_sort.asp

In [4]:
import numpy as np
arr = np.array([3,1,4,1,5,9,2,6])
print('Sorted asc:', np.sort(arr))
print('Sorted desc:', np.sort(arr)[::-1])

Sorted asc: [1 1 2 3 4 5 6 9]
Sorted desc: [9 6 5 4 3 2 1 1]


In [5]:
arr2d = np.array([[3,1,2],[6,4,5]])
print('Sort by row:\n', np.sort(arr2d))
print('Sort by col:\n', np.sort(arr2d, axis=0))

Sort by row:
 [[1 2 3]
 [4 5 6]]
Sort by col:
 [[3 1 2]
 [6 4 5]]


In [6]:
idx = np.argsort(arr)
print('argsort:', idx)
print('arr via argsort:', arr[idx])
print('Sorted strings:', np.sort(np.array(['banana','apple','cherry'])))

argsort: [1 3 6 0 2 4 7 5]
arr via argsort: [1 1 2 3 4 5 6 9]
Sorted strings: ['apple' 'banana' 'cherry']
