# Task 28 – NumPy: Create Arrays
**Reference:** https://www.w3schools.com/python/numpy_creating_arrays.asp

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print('1D:', arr1)

1D: [1 2 3 4 5]


In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print('2D:\n', arr2)

2D:
 [[1 2 3]
 [4 5 6]]


In [4]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('3D shape:', arr3.shape)

3D shape: (2, 2, 2)


In [5]:
print('zeros:\n', np.zeros((2, 3)))
print('ones:\n', np.ones((2, 3)))
print('arange:', np.arange(0, 10, 2))
print('linspace:', np.linspace(0, 1, 5))
print('identity:\n', np.eye(3))
print('full:', np.full((2, 3), 7))

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
full: [[7 7 7]
 [7 7 7]]
