# Task 34 – NumPy: Array Reshaping
**Reference:** https://www.w3schools.com/python/numpy_array_reshape.asp

In [1]:
import numpy as np
arr = np.arange(1, 13)
print('Original:', arr)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
print('Reshape (3,4):\n', arr.reshape(3, 4))
print('Reshape (2,3,2):\n', arr.reshape(2, 3, 2))

Reshape (3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape (2,3,2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
arr2d = np.array([[1,2,3],[4,5,6]])
print('flatten:', arr2d.flatten())
print('ravel:', arr2d.ravel())
print('Transpose:\n', arr2d.T)

flatten: [1 2 3 4 5 6]
ravel: [1 2 3 4 5 6]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
