# Task 36 – NumPy: Matrix Joining
**Reference:** https://www.w3schools.com/python/numpy_array_join.asp

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print('concatenate:', np.concatenate((a, b)))
print('stack:\n', np.stack((a, b)))
print('hstack:', np.hstack((a, b)))
print('vstack:\n', np.vstack((a, b)))

concatenate: [1 2 3 4 5 6]
stack:
 [[1 2 3]
 [4 5 6]]
hstack: [1 2 3 4 5 6]
vstack:
 [[1 2 3]
 [4 5 6]]


In [2]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print('concat axis=0 (rows):\n', np.concatenate((x,y), axis=0))
print('concat axis=1 (cols):\n', np.concatenate((x,y), axis=1))

concat axis=0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concat axis=1 (cols):
 [[1 2 5 6]
 [3 4 7 8]]
