# Task 30 – NumPy: Array Slicing
**Reference:** https://www.w3schools.com/python/numpy_array_slicing.asp

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print('arr[1:5]:', arr[1:5])
print('arr[4:]:', arr[4:])
print('arr[:4]:', arr[:4])
print('arr[::2]:', arr[::2])
print('arr[::-1]:', arr[::-1])

arr[1:5]: [2 3 4 5]
arr[4:]: [5 6 7]
arr[:4]: [1 2 3 4]
arr[::2]: [1 3 5 7]
arr[::-1]: [7 6 5 4 3 2 1]


In [2]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('All rows, cols 0:2:\n', arr2d[:, 0:2])
print('Rows 0:2, all cols:\n', arr2d[0:2, :])
print('Row 1:', arr2d[1, :])
print('Col 2:', arr2d[:, 2])

All rows, cols 0:2:
 [[1 2]
 [4 5]
 [7 8]]
Rows 0:2, all cols:
 [[1 2 3]
 [4 5 6]]
Row 1: [4 5 6]
Col 2: [3 6 9]
